### ISSUE TITLE
XP cant be got in player battles sense last restart.

### ISSUE THREAD

**Issue by FBIAgentTimmy** [NebulaMC-GG/Support#1332]
please tell me this is a bug im about to cry.

**Comment by fatyg5** [comment]
Unfortunately this is due to gym battle implementation. We do not want gyms leveling up people who forgot to lock their Pokemon levels. This is also in agreement with the Pokemon online trainer battling.

I also do not think abusing pvp for exp for your Pokemon is something we should have on the server, especially with healing over time, players could kill their opponents full team of high levels have their opponent walk a bit, get the team up to 1hp each, and then rebattle for quick exp.
