### ISSUE TITLE
Legendary despawning

### ISSUE THREAD

**Issue by UncleanCreams23** [NebulaMC-GG/Support#1401]
Had a wild Zamza doggo spawn on me, while I was stood there negotiating its sale it just disappeared in front of me

**Comment by CenizaRey** [comment]
It’s frowned upon by staff to sell teleports to master ball loots, let alone to wild legendaries. The only right you have to a legendary that spawns on you is that you get to catch it. Since you didn’t catch it, it technically isn’t yours to claim a ticket for because it was never *your* pokemon. Sorry for the sad news :(
