### ISSUE TITLE
Hoppers wont place

### ISSUE THREAD

**Issue by Mack4676** [NebulaMC-GG/Support#1485]
I've been trying to place hoppers and it lets me "place them" and the item is taken from my inventory but no hopper is shown in the block I placed it in. I tried mining the block as well and nothing was there except for the dirt below

**Comment by Menno165** [comment]
After doing some tests (Below) I guess it is a client sides issue and was solved by having Mack reboot his mc + launcher. After doing this he was able to place them in the claims again.

_Successful trying to place in my own claim, having a premier rank do it in their claim + in a trusted one_

Side note: While this was occurring, he was only able to place it in the wild, his own claim was not working. Leaving this here since I believe this information can be used for future cases with this issue for comparison.

**Comment by Menno165** [comment]
Closing the issue as there have not been any reports about it.
