### ISSUE TITLE
/hunts Impossible combinations and high requirements on lower tiers.

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Support#1605]
/hunts appears to pull pokemon and attributes at complete random creating hunts for many impossible pokemon to catch.
It has asked for 
Legendary pokemon
Fossils (dont spawn)
Baby Pokemon (dont spawn)
Impossible genders (Female Gallade, Male Floette)

Also iv's required have no upper bounds on any of the tiers resulting in some common hunts asking for 90-100% iv poke's. 

Its my personal opinion that hunt iv's shouldn't be above 75% for the rarest tiers and much less for the lower tiers.

Some Screenshots:
![ApplicationFrameHost_jWR9rxOkeb](https://user-images.githubusercontent.com/17133410/177800251-5e9504b3-bce3-4239-ace9-511862bc1cd5.png)
![ApplicationFrameHost_2AnQuLoN6E](https://user-images.githubusercontent.com/17133410/177800263-4a1d8e4b-0511-4f56-ab23-2fdb58b9ea56.png)
![ApplicationFrameHost_ajrzt6r5RO](https://user-images.githubusercontent.com/17133410/177800271-9dd9a800-df43-409d-b2b3-2accaeb42564.png)
![ApplicationFrameHost_QKjXIt6AyZ](https://user-images.githubusercontent.com/17133410/177800276-64e24f6c-a3c0-407e-abee-85d60d832157.png)
![ApplicationFrameHost_4jMkdp7Q6M](https://user-images.githubusercontent.com/17133410/177800286-de565814-54a6-4979-920e-8e4f8402f120.png)

**Comment by Menno165** [comment]
Hello there,

Thank you for the post, the team is currently looking at tiers and what we can change.

Example of changes we are *planning* to make are the following:
 *(so not set in stone)*

- Removing 1st, 2nd and 3rd evolution line Pokémon from certain tiers.
- Removing legendary/mythical Pokémon
- Removing Ultra Beast Pokémon from certain tiers
- Removing certain rare or hard to get Pokémon from certain tiers
- IV Requirement for each hunts.
- Temporally disabling Gallade and Floette because of gender issues.
- Removing all Pokémon that can not spawn naturally. (Examples below:)
> Almost all baby Pokémon,
> Fossil Pokémon
> Mewtwo, Melmetal and the Urshifu's
> All Pokémon that need an evolution item + don't have a biome.

**Comment by Vavalur** [comment]
> * Temporally disabling Gallade and Floette because of gender issues.

Then you should also temporarily disable genderless pokemon as those hunts are also impossible to complete as the hunt wants them to have a gender.

**Comment by Menno165** [comment]
We have a list of all the Pokémon with a gender issue and are currently working on it.
I made sure to update the comments above to prevent confusion in the future.

**Comment by HackuJacku** [comment]
These issues are now resolved, thank you for the report :)
