### ISSUE TITLE
DEXRANK MEGATHREAD

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Support#1621]
If you are having any issues with the dexranks (rank not redeeming, rank in tab is different than in chat, rewards are not correct) please comment under this with this format:

IGN:
Server:
Issue:
(Optional) Screenshot Proof/Chat Log:

**Comment by Smith-sonite** [comment]
IGN: Smithsonite_
Server: Orion
Issue:
- Luxury and Dream don't show properly on tab, showing Ultra instead
- Luxury has only 4 homes, not 5

**Comment by AwesomeQ2003** [comment]
IGN: Q_man2003
Server: Atlas
Issue:

- Similar to the other post ranks are not showing up properly on tab
- I have claimed the Ultra Rank but have not received the kit or the rank in chat or in tab

**Comment by TheNahgooyen** [comment]
IGN: Miyon
Server: Atlas
Issue:

- [Poke] Rank did not apply when claiming the applicable reward, cannot use kit or see in tab and chat
- Other rewards received as normal (PC, Healer, etc.)

**Comment by Hades-33** [comment]
IGN: Hades33_
Server: Atlas
Issue: I unlocked the Luxury Dex Rank, but when I try to use the kit it says I haven’t unlocked it

**Comment by mnky-frt** [comment]
IGN: Sinders
Server: Atlas
Issue: I have over 2.5% completed in dex but I cannot claim the Poke title

![image](https://user-images.githubusercontent.com/85257491/178166166-69e6ac1b-432a-4485-b51f-171ed3b2f553.png)
![image](https://user-images.githubusercontent.com/85257491/178166171-724a2e6f-2fea-4d89-8816-0a43f3dc7b6b.png)
![image](https://user-images.githubusercontent.com/85257491/178166172-70a1ad72-8358-49f1-9dbe-eecc426effa2.png)

**Comment by Xerkas** [comment]
IGN: Xerkas
Server: Atlas
Issue:
[Poke] Rank did not apply when claiming the applicable reward, cannot use kit or see in tab and chat. Other rewards received as normal (PC, Healer, etc.)

**Comment by Smith-sonite** [comment]
IGN: Smithsonite_
Server: Orion
Issue:
Master rank perms not updating properly. I got the one-time kit but I don't have access to the weekly one. Also the tag in chat is unchanged from [Beast].

**Comment by MilkNotDry** [comment]
IGN: MilkNotDry
Server: Atlas
Issue: Poke Rank was not issued after clearing the requirement

**Comment by BrennenChapman** [comment]
didnt get the modifiers from beast or master dex rewards because they are broken atm. or the dragon skull. and i dont have access to the beast and master weekly kits. 
![image](https://user-images.githubusercontent.com/24552190/178272333-de93d85c-fc7f-4669-aab8-3d0e0ae262f5.png)
![image](https://user-images.githubusercontent.com/24552190/178272399-20373994-ae9e-4494-bd38-53f93f50bd17.png)

**Comment by ashhpng** [comment]
IGN:4shh_
Server: Atlas
Issue:

Hit 10% of Pokémon caught for the dexrank but Great rank not showing

**Comment by mnky-frt** [comment]
ign: mnky_frt
server: atlas
issue: did not receive dream rank upon hitting 60% dex completion. i was able to claim rewards but i cannot claim the weekly kit because the rewards did not give me the dream rank
![image](https://user-images.githubusercontent.com/85257491/178782599-943f16d5-3339-47d2-9edc-4796662f696b.png)
![image](https://user-images.githubusercontent.com/85257491/178782652-5116203e-10e5-4f65-ba10-b787a015912e.png)
![image](https://user-images.githubusercontent.com/85257491/178782742-bab2d2f2-1b2e-43ce-9e14-491e13ee5f8d.png)

**Comment by Hades-33** [comment]
I've already posted about my dex rank issue, but i've noticed my houses say 7/4 and i don't wanna upgrade to Nova until i can get that fixed just incase its a continuing issue

**Comment by Caelune1204** [comment]
IGN: Caelune1204
Server: Orion
Issue: Achieved Ultra rank yesterday and claimed the rewards, but rank doesn't show in chat nor am I able to claim the weekly kit.

**Comment by innqmorato** [comment]
Server: Orion
Nickname: innqmorato
Issue: claimed luxury rank but can't claim the kit and neither got the tag and also some wrong rewards like 16 ub instead of 32
![2022-07-14_14 01 59](https://user-images.githubusercontent.com/109287888/178978869-57edba9e-3bcd-48aa-88df-f8c4bedee86e.png)
![2022-07-14_14 04 24](https://user-images.githubusercontent.com/109287888/178978873-c595dfa0-e0ea-43b8-856e-6c7ad76e1fd8.png)

**Comment by Specter882** [comment]
IGN - Specter
Server - Orion
No access to weekly Beast kit after claiming Beast rank

**Comment by Xerkas** [comment]
IGN: Xerkas
Server - Atlas
Missing Premier Rank and weekly rewards for Premier and Ultra Rank
![image](https://user-images.githubusercontent.com/109047353/179328376-9b660a96-09d1-448d-8def-ebb2e81f9466.png)
![image](https://user-images.githubusercontent.com/109047353/179328388-c70fa1e6-bafc-495c-8555-5a364e867e2a.png)
![image](https://user-images.githubusercontent.com/109047353/179328395-e7717c86-da25-44c0-ae96-73cd80d74f4f.png)

**Comment by JuniperSpringstick** [comment]
IGN: JuniperSpringsti
Server: Atlas
Issue: I earned the dreamer rank but it never updated my rank or updated it to where i could claim the monthly rewards for it 
![2022-07-16_10 07 44](https://user-images.githubusercontent.com/108998202/179359450-ce215872-03e9-42c2-8bc6-4be52d7ebe82.png)

**Comment by rygwan** [comment]
IGN:rygwan
Server: Atlas
Issue: I have  all the awards for this rank but I am not of the rank 'great'
![image](https://user-images.githubusercontent.com/109437252/179370021-011e7a36-5a78-4482-8384-ea0f8f4a793e.png)

**Comment by MissElyri** [comment]
A fix for this has been applied to Atlas and will be applied to other servers (soonTM), pending server restart. Please check the discord changeling for further information.

**Comment by toofuriouz** [comment]
![image](https://user-images.githubusercontent.com/85075804/180034563-564d1457-95aa-4df8-85ec-4d0464d93878.png)
